//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/InputTeclado.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputTeclado: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputTeclado()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputTeclado"",
    ""maps"": [
        {
            ""name"": ""Teclado"",
            ""id"": ""35aea8f3-5153-4207-a378-d368d4f41030"",
            ""actions"": [
                {
                    ""name"": ""Album"",
                    ""type"": ""Button"",
                    ""id"": ""eb620c16-f19b-48ae-bb19-77f88d55cf52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1e89742-aebe-4b21-98bb-8c97537e38b2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Album"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Teclado
        m_Teclado = asset.FindActionMap("Teclado", throwIfNotFound: true);
        m_Teclado_Album = m_Teclado.FindAction("Album", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Teclado
    private readonly InputActionMap m_Teclado;
    private List<ITecladoActions> m_TecladoActionsCallbackInterfaces = new List<ITecladoActions>();
    private readonly InputAction m_Teclado_Album;
    public struct TecladoActions
    {
        private @InputTeclado m_Wrapper;
        public TecladoActions(@InputTeclado wrapper) { m_Wrapper = wrapper; }
        public InputAction @Album => m_Wrapper.m_Teclado_Album;
        public InputActionMap Get() { return m_Wrapper.m_Teclado; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TecladoActions set) { return set.Get(); }
        public void AddCallbacks(ITecladoActions instance)
        {
            if (instance == null || m_Wrapper.m_TecladoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TecladoActionsCallbackInterfaces.Add(instance);
            @Album.started += instance.OnAlbum;
            @Album.performed += instance.OnAlbum;
            @Album.canceled += instance.OnAlbum;
        }

        private void UnregisterCallbacks(ITecladoActions instance)
        {
            @Album.started -= instance.OnAlbum;
            @Album.performed -= instance.OnAlbum;
            @Album.canceled -= instance.OnAlbum;
        }

        public void RemoveCallbacks(ITecladoActions instance)
        {
            if (m_Wrapper.m_TecladoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITecladoActions instance)
        {
            foreach (var item in m_Wrapper.m_TecladoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TecladoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TecladoActions @Teclado => new TecladoActions(this);
    public interface ITecladoActions
    {
        void OnAlbum(InputAction.CallbackContext context);
    }
}
